name: CI/CD for Growtrack

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ---------- Backend ----------
      - name: Clean backend node_modules
        working-directory: ./backend
        run: rm -rf node_modules

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run backend tests
        working-directory: ./backend
        run: npm test

      - name: Check backend health endpoint
        run: |
          nohup npm run dev --prefix backend > /dev/null 2>&1 &
          sleep 10
          curl --fail http://localhost:3000/health

      # ---------- Frontend ----------
      - name: Clean frontend node_modules
        working-directory: ./frontend
        run: rm -rf node_modules

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm run test:unit

  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t nour537/growtrack-backend:${{ env.sha_short }} ./backend
          docker tag nour537/growtrack-backend:${{ env.sha_short }} nour537/growtrack-backend:latest
          docker push nour537/growtrack-backend:${{ env.sha_short }}
          docker push nour537/growtrack-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t nour537/growtrack-frontend:${{ env.sha_short }} ./frontend
          docker tag nour537/growtrack-frontend:${{ env.sha_short }} nour537/growtrack-frontend:latest
          docker push nour537/growtrack-frontend:${{ env.sha_short }}
          docker push nour537/growtrack-frontend:latest
