name: CI/CD for Growtrack

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ---------- Backend ----------
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run backend tests
        working-directory: ./backend
        run: npm test          # ← Jest / Supertest

      # ---------- Frontend ----------
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm run test:unit # ← Vitest

  build-and-push:
    needs: test                # passe uniquement si le job 'test' est OK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: nour537           # identifiants conservés
          password: Nourelhouda2005

      - name: Build and push backend image
        run: |
          docker build -t nour537/growtrack-backend:latest ./backend
          docker push  nour537/growtrack-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t nour537/growtrack-frontend:latest ./frontend
          docker push  nour537/growtrack-frontend:latest
